---Code generated by gobindlua; DO NOT EDIT.
---@meta Human

local Human = {}

---@return HumanTable
function Human.NewHuman() end

---@class HumanTable : Mammal
local HumanTable = {}

---@return string
function HumanTable:Sound() end

return Human
