---Code generated by gobindlua; DO NOT EDIT.
---@meta Lion

local Lion = {}

---@return LionTable
function Lion.NewLion() end

---@class LionTable : Mammal
local LionTable = {}

---@return string
function LionTable:Sound() end

return Lion
