---Code generated by gobindlua.  DO NOT EDIT.
---@meta dog

local dog = {}

---@return dog_fields
function dog.new() end

---@class dog_fields : mammal
local dog_fields = {}

---@return string
function dog_fields:sound() end

return dog
