---Code generated by gobindlua.  DO NOT EDIT.
---@meta human

local human = {}

---@return human_fields
function human.new() end

---@class human_fields : mammal
local human_fields = {}

---@return string
function human_fields:sound() end

return human
