---Code generated by gobindlua.  DO NOT EDIT.
---@meta lion

local lion = {}

---@return lion_fields
function lion.new() end

---@class lion_fields : mammal
local lion_fields = {}

---@return string
function lion_fields:sound() end

return lion
