---Code generated by gobindlua; DO NOT EDIT.
---@meta primitive_struct

local primitive_struct = {}

---@return primitive_struct_fields
function primitive_struct.new() end

---@class primitive_struct_fields
---@field public my_bool boolean
---@field public my_int number
---@field public my_int64 number
---@field public my_float number
---@field public my_string string
---@field public my_specialized_int number
local primitive_struct_fields = {}

---@param divisor number
---@return number
function primitive_struct_fields:divide_my_int(divisor) end

---@param i number
function primitive_struct_fields:set_specialized_int(i) end

return primitive_struct
