---Code generated by gobindlua; DO NOT EDIT.
---@meta PrimitiveStruct

local PrimitiveStruct = {}

---@return PrimitiveStructTable
function PrimitiveStruct.NewPrimitiveStruct() end

---@class PrimitiveStructTable
---@field public MyBool boolean
---@field public MyInt number
---@field public MyInt64 number
---@field public MyFloat number
---@field public MyString string
---@field public MySpecializedInt number
local PrimitiveStructTable = {}

---@param divisor number
---@return number
function PrimitiveStructTable:DivideMyInt(divisor) end

---@param i number
function PrimitiveStructTable:SetSpecializedInt(i) end

return PrimitiveStruct
