---Code generated by gobindlua.  DO NOT EDIT.
---@meta sub

local sub = {}

---@param str string
---@return sub_fields
function sub.new(str) end

---@class sub_fields
---@field public str string
local sub_fields = {}

return sub
