---Code generated by gobindlua; DO NOT EDIT.
---@meta SomeStruct

local SomeStruct = {}

---@class SomeStructTable
---@field public A table<string,table<string,string[]>>
---@field public B SubTable
---@field public C SubTable
---@field public D number[][]
---@field public E SubTable[][]
---@field public F table<SubTable,number>[]
local SomeStructTable = {}

return SomeStruct
