---Code generated by gobindlua; DO NOT EDIT.
---@meta some_struct

local some_struct = {}

---@class some_struct_fields
---@field public a table<string,table<string,string[]>>
---@field public b sub_fields
---@field public c sub_fields
---@field public d number[][]
---@field public e sub_fields[][]
---@field public f table<sub_fields,number>[]
local some_struct_fields = {}

return some_struct
