---Code generated by gobindlua; DO NOT EDIT.
---@meta Sub

local Sub = {}

---@param str string
---@return SubTable
function Sub.NewSub(str) end

---@class SubTable
---@field public Str string
local SubTable = {}

return Sub
