// Code generated by gobindlua; DO NOT EDIT.
package mammallist

import (
	"fmt"

	"github.com/ChrisTrenkamp/gobindlua"
	"github.com/ChrisTrenkamp/gobindlua/doc/05.Interfaces/mammal"
	lua "github.com/yuin/gopher-lua"
)

func (goType *MammalList) LuaModuleName() string {
	return "MammalList"
}

func (goType *MammalList) LuaModuleLoader(L *lua.LState) int {
	staticMethodsTable := L.NewTable()
	L.SetField(staticMethodsTable, "NewMammalList", L.NewFunction(luaConstructorMammalListNewMammalList))

	L.Push(staticMethodsTable)

	return 1
}

func (goType *MammalList) LuaRegisterGlobalMetatable(L *lua.LState) {
	fieldsTable := L.NewTypeMetatable(goType.LuaMetatableType())
	L.SetGlobal(goType.LuaMetatableType(), fieldsTable)
	L.SetField(fieldsTable, "__index", L.NewFunction(luaAccessMammalList))
	L.SetField(fieldsTable, "__newindex", L.NewFunction(luaSetMammalList))
}

func luaConstructorMammalListNewMammalList(L *lua.LState) int {

	r0 := NewMammalList()

	L.Push(gobindlua.NewUserData(&r0, L))

	return 1
}

func (r *MammalList) LuaMetatableType() string {
	return "MammalListTable"
}

func luaCheckMammalList(param int, L *lua.LState) *MammalList {
	ud := L.CheckUserData(param)
	v, ok := ud.Value.(*MammalList)
	if !ok {
		gobindlua.CastArgError(L, 1, "MammalList", ud.Value)
	}
	return v
}

func luaAccessMammalList(L *lua.LState) int {
	recv := luaCheckMammalList(1, L)
	p2 := L.CheckString(2)

	switch p2 {
	case "Pet":
		L.Push(gobindlua.NewUserData(recv.Pet, L))

	case "NonPets":
		L.Push(gobindlua.NewUserData(&gobindlua.GblSlice{
			Slice: recv.NonPets,
			Len:   func() int { return len(recv.NonPets) },
			Index: func(idx0 int) lua.LValue { return gobindlua.NewUserData((recv.NonPets)[idx0], L) },
			SetIndex: func(idx0 int, val0 lua.LValue) {

				t0_ud, ok := val0.(*lua.LUserData)

				if !ok {
					gobindlua.TableElemCastError(L, 1, "mammal.Mammal", val0)
				}

				t0, ok := t0_ud.Value.(mammal.Mammal)

				if !ok {
					gobindlua.TableElemCastError(L, 1, "mammal.Mammal", val0)
				}

				(recv.NonPets)[idx0] = t0
			},
		}, L))

	default:
		L.Push(lua.LNil)
	}

	return 1
}

func luaSetMammalList(L *lua.LState) int {
	recv := luaCheckMammalList(1, L)
	p2 := L.CheckString(2)

	switch p2 {
	case "Pet":

		ud, ok := L.CheckUserData(3).Value.(mammal.Mammal)

		if !ok {
			gobindlua.CastArgError(L, 3, "mammal.Mammal", L.CheckUserData(3))
		}

		recv.Pet = ud

	case "NonPets":

		ud, err := gobindlua.MapLuaArrayOrTableToGoSlice[mammal.Mammal](L.CheckAny(3), 0, func(val0 lua.LValue) mammal.Mammal {

			v0_ud, ok := val0.(*lua.LUserData)

			if !ok {
				gobindlua.TableElemCastError(L, 1, "mammal.Mammal", val0)
			}

			v0, ok := v0_ud.Value.(mammal.Mammal)

			if !ok {
				gobindlua.TableElemCastError(L, 1, "mammal.Mammal", val0)
			}

			return v0
		})

		if err != nil {
			L.ArgError(3, err.Error())
		}

		recv.NonPets = ud

	default:
		L.ArgError(2, fmt.Sprintf("unknown field %s", p2))
	}

	return 0
}
