---Code generated by gobindlua; DO NOT EDIT.
---@meta mammal_list

local mammal_list = {}

---@return mammal_list_fields
function mammal_list.new() end

---@class mammal_list_fields
---@field public pet mammal
---@field public non_pets mammal[]
local mammal_list_fields = {}

return mammal_list
