---Code generated by gobindlua; DO NOT EDIT.
---@meta MammalList

local MammalList = {}

---@return MammalListTable
function MammalList.NewMammalList() end

---@class MammalListTable
---@field public Pet Mammal
---@field public NonPets Mammal[]
local MammalListTable = {}

return MammalList
