---Code generated by gobindlua; DO NOT EDIT.
---@meta ArrayStruct

local ArrayStruct = {}

---@param elems number[]
---@return ArrayStructTable
function ArrayStruct.NewArrayStruct(elems) end

---@class ArrayStructTable
---@field public Elements number[]
local ArrayStructTable = {}

---@param j number[]
function ArrayStructTable:SetElements(j) end

---@param j number[]
function ArrayStructTable:SetElementsFromSubpackage(j) end

---@return string
function ArrayStructTable:String() end

return ArrayStruct
