---Code generated by gobindlua; DO NOT EDIT.
---@meta Dog

local Dog = {}

---@return DogTable
function Dog.NewDog() end

---@class DogTable : Mammal
local DogTable = {}

---@return string
function DogTable:Sound() end

return Dog
