---Code generated by gobindlua; DO NOT EDIT.
---@meta Matrix

local Matrix = {}

---@param elems number[][]
---@return MatrixTable
function Matrix.NewMatrixFrom(elems) end

---@class MatrixTable
---@field public Elements number[][]
local MatrixTable = {}

---@return string
function MatrixTable:String() end

return Matrix
