---Code generated by gobindlua; DO NOT EDIT.
---@meta Vector

local Vector = {}

---@param elems number[]
---@return VectorTable
function Vector.NewVectorFrom(elems) end

---@param ... number
---@return VectorTable
function Vector.NewVectorVariadic(...) end

---@class VectorTable
---@field public Elements number[]
local VectorTable = {}

---@param o VectorTable
---@return number
function VectorTable:InnerProduct(o) end

---@param o VectorTable
---@return MatrixTable
function VectorTable:OuterProduct(o) end

return Vector
