---Code generated by gobindlua; DO NOT EDIT.
---@meta fn_container

local fn_container = {}

---@param fn function
---@return fn_container_fields
function fn_container.new(fn) end

---@class fn_container_fields
---@field public fn function
local fn_container_fields = {}

return fn_container
