---Code generated by gobindlua; DO NOT EDIT.
---@meta functions

local functions = {}
---@param ... any
function functions.PrintMe(...) end

---@param s string
---@param spl string
---@return string[]
function functions.Split(s, spl) end

---@param str string
---@param pad number
---@return string
function functions.GoLeftPad(str, pad) end

---@param fn function
function functions.DoFunc(fn) end

return functions
