---Code generated by gobindlua; DO NOT EDIT.
---@meta FnContainer

local FnContainer = {}

---@param fn function
---@return FnContainerTable
function FnContainer.NewFnContainer(fn) end

---@class FnContainerTable
---@field public Fn function
local FnContainerTable = {}

return FnContainer
