---Code generated by gobindlua; DO NOT EDIT.
---@meta functions

local functions = {}
---@param ... any
function functions.print_me(...) end

---@param s string
---@param spl string
---@return string[]
function functions.split(s, spl) end

return functions
