---Code generated by gobindlua.  DO NOT EDIT.
---@meta vector

local vector = {}

---@param elems number[]
---@return vector_fields
function vector.new_from(elems) end

---@param ... number
---@return vector_fields
function vector.new_variadic(...) end

---@class vector_fields
---@field public elements number[]
local vector_fields = {}

---@param o vector_fields
---@return number
function vector_fields:inner_product(o) end

---@param o vector_fields
---@return matrix_fields
function vector_fields:outer_product(o) end

return vector
