---Code generated by gobindlua.  DO NOT EDIT.
---@meta array_struct

local array_struct = {}

---@param elems number[]
---@return array_struct_fields
function array_struct.new(elems) end

---@class array_struct_fields
---@field public elements number[]
local array_struct_fields = {}

---@param j number[]
function array_struct_fields:set_elements(j) end

---@return string
function array_struct_fields:string() end

return array_struct
