---Code generated by gobindlua.  DO NOT EDIT.
---@meta matrix

local matrix = {}

---@param elems number[][]
---@return matrix_fields
function matrix.new_from(elems) end

---@class matrix_fields
---@field public elements number[][]
local matrix_fields = {}

---@return string
function matrix_fields:string() end

return matrix
