---Code generated by gobindlua.  DO NOT EDIT.
---@meta user

local user = {}

---@param name string
---@param age number
---@param email string
---@return user_fields
function user.new(name, age, email) end

---@class user_fields
---@field public name string
---@field public age number
---@field public email string
local user_fields = {}

return user
