---Code generated by gobindlua; DO NOT EDIT.
---@meta User

local User = {}

---@param name string
---@param age number
---@param email string
---@return UserTable
function User.NewUser(name, age, email) end

---@class UserTable
---@field public Name string
---@field public Age number
---@field public Email string
local UserTable = {}

return User
