---Code generated by gobindlua; DO NOT EDIT.
---@meta user_database

local user_database = {}

---@return user_database_fields
function user_database.new() end

---@param users table<number,user_fields>
---@return user_database_fields
function user_database.new_from(users) end

---@class user_database_fields
---@field public users table<number,user_fields>
local user_database_fields = {}

return user_database
