---Code generated by gobindlua; DO NOT EDIT.
---@meta UserDatabase

local UserDatabase = {}

---@return UserDatabaseTable
function UserDatabase.NewUserDatabase() end

---@param users table<number,UserTable>
---@return UserDatabaseTable
function UserDatabase.NewUserDatabaseFrom(users) end

---@class UserDatabaseTable
---@field public Users table<number,UserTable>
local UserDatabaseTable = {}

return UserDatabase
